services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-point-app
    ports:
      - "${PORT:-3333}:3333"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
